[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

; Uncomment to enable active countermeasures (LEGAL AUTHORIZATION REQUIRED)
; build_flags = -DENABLE_COUNTERMEASURES

lib_deps = 
    olikraus/U8g2@^2.35.9
    SPI
    Wire

upload_speed = 921600
monitor_filters = esp32_exception_decoder
