#!/usr/bin/env python3
"""Validate the canonical Rev C contract and generate its firmware pin map."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = ROOT / "hardware" / "rev_c" / "hardware_manifest.json"
DEFAULT_HEADER = ROOT / "src" / "generated" / "hardware_rev_c.h"


class ManifestError(ValueError):
    """The Rev C hardware contract violates a firmware invariant."""


def require_object(parent: dict[str, Any], name: str) -> dict[str, Any]:
    value = parent.get(name)
    if not isinstance(value, dict) or not value:
        raise ManifestError(f"{name} must be a non-empty object")
    return value


def load_manifest(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ManifestError(f"cannot load {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ManifestError("manifest root must be an object")
    return value


def validate_manifest(manifest: dict[str, Any]) -> None:
    if manifest.get("schema_version") != 1:
        raise ManifestError("schema_version must be 1")

    design = require_object(manifest, "design")
    firmware = require_object(manifest, "firmware")
    mcu = require_object(manifest, "mcu")
    signals = require_object(manifest, "signals")
    reserved = require_object(manifest, "reserved_gpio")

    if design.get("revision") != "C" or design.get("orderable") is not False:
        raise ManifestError("Rev C must remain a non-orderable revision-C design")
    if (
        mcu.get("mpn") != "ESP32-S3-WROOM-1-N16R8"
        or mcu.get("flash_mb") != 16
        or mcu.get("psram_mb") != 8
    ):
        raise ManifestError("Rev C requires ESP32-S3-WROOM-1-N16R8 (16 MB flash, 8 MB octal PSRAM)")
    if firmware.get("board_macro") != "BOARD_SKYSWEEP32_REV_C":
        raise ManifestError("unexpected Rev C board macro")
    if firmware.get("profile_macro") != "PROFILE_PASSIVE_MONITOR":
        raise ManifestError("unexpected Rev C firmware profile")

    used_gpio: dict[int, str] = {}
    used_macros: dict[str, str] = {}
    for name, signal in signals.items():
        if not isinstance(signal, dict):
            raise ManifestError(f"signal {name} must be an object")
        gpio = signal.get("gpio")
        macro = signal.get("firmware_macro")
        if not isinstance(gpio, int) or not 0 <= gpio <= 48:
            raise ManifestError(f"signal {name} has invalid GPIO {gpio!r}")
        if gpio in used_gpio:
            raise ManifestError(f"GPIO{gpio} is shared by {used_gpio[gpio]} and {name}")
        used_gpio[gpio] = name
        if macro is None:
            if name not in {"USB_D_MINUS", "USB_D_PLUS"}:
                raise ManifestError(f"only native USB signals may omit a firmware macro: {name}")
        elif not isinstance(macro, str) or not macro.startswith("PIN_"):
            raise ManifestError(f"signal {name} has invalid firmware macro")
        elif macro in used_macros:
            raise ManifestError(f"firmware macro {macro} is shared by {used_macros[macro]} and {name}")
        else:
            used_macros[macro] = name

    reserved_pins = {int(pin) for pin in reserved}
    permitted_reserved = {
        signals["USB_D_MINUS"]["gpio"],
        signals["USB_D_PLUS"]["gpio"],
    }
    collisions = (set(used_gpio) & reserved_pins) - permitted_reserved
    if collisions:
        raise ManifestError(f"peripheral signals use reserved GPIOs: {sorted(collisions)}")

    expected_features = {
        "MODULE_SX1281",
        "MODULE_CC1101",
        "MODULE_RX5808",
        "MODULE_BATTERY_GAUGE",
        "MODULE_OLED",
        "MODULE_WEB_SERVER",
        "MODULE_REMOTE_ID",
        "MODULE_GPS",
        "MODULE_SD_CARD",
        "MODULE_ESPNOW",
    }
    if set(firmware.get("features", [])) != expected_features:
        raise ManifestError("Rev C feature set differs from the reviewed passive profile")
    forbidden_features = {"MODULE_NRF24", "MODULE_LORA", "MODULE_ML", "ENABLE_COUNTERMEASURES"}
    if forbidden_features & set(firmware.get("features", [])):
        raise ManifestError("Rev C contains a forbidden or unsupported feature")


def render_header(manifest: dict[str, Any], manifest_path: Path) -> str:
    firmware = manifest["firmware"]
    relative_manifest = manifest_path.resolve().relative_to(ROOT).as_posix()
    lines = [
        "// Generated by tools/development/generate_rev_c_pinmap.py; do not edit.",
        f"// Source: {relative_manifest}",
        "#pragma once",
        "",
        f"#define {firmware['board_macro']} 1",
        f"#define {firmware['profile_macro']} 1",
        "",
        *[f"#define {feature} 1" for feature in firmware["features"]],
        "",
    ]
    for name, signal in manifest["signals"].items():
        macro = signal.get("firmware_macro")
        if macro:
            lines.append(f"#define {macro:<22} {signal['gpio']:<2} // {name}")
    lines.extend(
        [
            "#define PIN_SD_MOSI           PIN_SPI_MOSI // shared SPI data",
            "#define PIN_SD_MISO           PIN_SPI_MISO // shared SPI data",
            "#define PIN_SD_SCK            PIN_SPI_SCK  // shared SPI clock",
        ]
    )
    lines.extend(
        [
            "",
            "#define GPS_BAUD_RATE          9600",
            "#define GPS_UPDATE_INTERVAL    1000",
            "",
            "#if defined(TIER_JUGGERNAUT) || defined(ENABLE_COUNTERMEASURES)",
            '#error "Rev C is passive-only and has no countermeasure hardware"',
            "#endif",
            "#if defined(MODULE_NRF24) || defined(MODULE_LORA) || defined(MODULE_ML)",
            '#error "Rev C does not implement nRF24L01+, LoRa, or TinyML hardware/features"',
            "#endif",
            "#ifdef MODULE_ACOUSTIC",
            '#error "Rev C does not route an I2S acoustic input"',
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    validate_manifest(manifest)
    rendered = render_header(manifest, args.manifest)
    if args.check:
        try:
            existing = args.output.read_text(encoding="utf-8")
        except OSError as exc:
            raise SystemExit(f"[FAIL] generated pin map missing: {exc}") from exc
        if existing != rendered:
            raise SystemExit(
                "[FAIL] generated Rev C pin map is stale; run "
                "python tools/development/generate_rev_c_pinmap.py"
            )
        print(f"[PASS] manifest and generated pin map agree: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"[PASS] validated {args.manifest}")
    print(f"[OK] generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
